[CmdletBinding()]
param(
    [string]$InputPath,
    [string]$OutputPath,
    [ValidateRange(32, 240)]
    [int]$Size = 168
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($InputPath)) {
    $InputPath = Join-Path $repoRoot 'firmware\assets\morgan-portrait.png'
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $repoRoot 'firmware\morgan_badge\morgan_avatar_rgb565.h'
}

$InputPath = [IO.Path]::GetFullPath($InputPath)
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
if (-not (Test-Path -LiteralPath $InputPath)) {
    throw "Avatar source not found: $InputPath"
}

Add-Type -AssemblyName System.Drawing
$source = [Drawing.Bitmap]::FromFile($InputPath)
$target = [Drawing.Bitmap]::new($Size, $Size, [Drawing.Imaging.PixelFormat]::Format24bppRgb)

try {
    $cropSize = [Math]::Min($source.Width, $source.Height)
    $sourceX = [int](($source.Width - $cropSize) / 2)
    $sourceY = [int](($source.Height - $cropSize) / 2)
    $graphics = [Drawing.Graphics]::FromImage($target)
    try {
        $graphics.CompositingMode = [Drawing.Drawing2D.CompositingMode]::SourceCopy
        $graphics.CompositingQuality = [Drawing.Drawing2D.CompositingQuality]::HighQuality
        $graphics.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $graphics.DrawImage(
            $source,
            [Drawing.Rectangle]::new(0, 0, $Size, $Size),
            [Drawing.Rectangle]::new($sourceX, $sourceY, $cropSize, $cropSize),
            [Drawing.GraphicsUnit]::Pixel
        )
    } finally {
        $graphics.Dispose()
    }

    $writer = [IO.StreamWriter]::new($OutputPath, $false, [Text.UTF8Encoding]::new($false))
    try {
        $writer.WriteLine('#pragma once')
        $writer.WriteLine('')
        $writer.WriteLine('#include <Arduino.h>')
        $writer.WriteLine('')
        $writer.WriteLine('// Generated by scripts/prepare-badge-avatar.ps1 from firmware/assets/morgan-portrait.png.')
        $writer.WriteLine("constexpr uint16_t kMorganAvatarWidth = $Size;")
        $writer.WriteLine("constexpr uint16_t kMorganAvatarHeight = $Size;")
        $writer.WriteLine('const uint16_t kMorganAvatarRgb565[] PROGMEM = {')

        $valuesOnLine = 0
        for ($y = 0; $y -lt $Size; $y++) {
            for ($x = 0; $x -lt $Size; $x++) {
                $pixel = $target.GetPixel($x, $y)
                $rgb565 = (($pixel.R -shr 3) -shl 11) -bor (($pixel.G -shr 2) -shl 5) -bor ($pixel.B -shr 3)
                if ($valuesOnLine -eq 0) {
                    $writer.Write('  ')
                }
                $writer.Write(('0x{0:X4}' -f $rgb565))
                $valuesOnLine++
                $isLastPixel = $x -eq $Size - 1 -and $y -eq $Size - 1
                if (-not $isLastPixel) {
                    $writer.Write(',')
                }
                if ($valuesOnLine -eq 12 -or $isLastPixel) {
                    $writer.WriteLine()
                    $valuesOnLine = 0
                } else {
                    $writer.Write(' ')
                }
            }
        }
        $writer.WriteLine('};')
    } finally {
        $writer.Dispose()
    }
} finally {
    $target.Dispose()
    $source.Dispose()
}

$generated = Get-Item -LiteralPath $OutputPath
Write-Output "Generated $($generated.FullName) ($($generated.Length) bytes, ${Size}x${Size} RGB565)."