import type { ChatCompletionTool } from 'openai/resources/chat';
import { analyzeBudgetVsActuals, getFinancialKPIs, detectAnomalies } from './financialTools';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function varianceEmoji(pct: number): string {
  if (pct > 10) return '🔴';
  if (pct > 5)  return '🟡';
  return '🟢';
}

function usd(value: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
}

function pctStr(value: number): string {
  return `${value >= 0 ? '+' : ''}${value.toFixed(1)}%`;
}

// ---------------------------------------------------------------------------
// 1. formatBudgetReport
// ---------------------------------------------------------------------------

export function formatBudgetReport(params: {
  period: string;
  include_charts: boolean;
}): string {
  const analysis = analyzeBudgetVsActuals({ period: params.period });
  const kpis     = getFinancialKPIs({ period: params.period });
  const { summary, table, anomalies } = analysis;

  const overallEmoji = varianceEmoji(Math.abs(summary.totalVariancePct));

  const lines: string[] = [
    `# 📊 Budget vs Actuals Report — ${params.period}`,
    `**Company:** ${analysis.company}  |  **Generated:** ${new Date().toUTCString()}`,
    '',
    '---',
    '',
    '## Executive Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total Budget | ${usd(summary.totalBudget)} |`,
    `| Total Actuals | ${usd(summary.totalActual)} |`,
    `| Net Variance | ${usd(summary.totalVariance)} (${pctStr(summary.totalVariancePct)}) ${overallEmoji} |`,
    `| Anomalies Detected | ${summary.anomalyCount} |`,
    `| Gross Margin | ${kpis.grossMarginPct}% |`,
    `| EBITDA | ${usd(kpis.ebitda)} |`,
    '',
    '---',
    '',
    '## Budget vs Actuals — Detail',
    '',
    '| Category | Budget | Actual | Variance | Var % | Status |',
    '|----------|--------|--------|----------|-------|--------|',
    ...table.map(r =>
      `| ${r.category} | ${usd(r.budget)} | ${usd(r.actual)} | ${usd(r.variance)} | ${pctStr(r.variancePct)} | ${varianceEmoji(r.variancePct)} |`,
    ),
    '',
  ];

  if (params.include_charts) {
    lines.push('> 📈 *Interactive charts available in the full dashboard portal.*', '');
  }

  lines.push(
    '---',
    '',
    '## Key Anomalies',
    '',
  );

  if (anomalies.length === 0) {
    lines.push('✅ No categories exceeded the 10% over-budget threshold this period.', '');
  } else {
    anomalies.forEach(a => {
      lines.push(
        `- 🔴 **${a.category}**: ${pctStr(a.variancePct)} over budget (${usd(a.variance)} excess spend)`,
      );
    });
    lines.push('');
  }

  lines.push(
    '---',
    '',
    '## Recommendations',
    '',
    ...anomalies.map(
      a => `- Review **${a.category}** spend drivers and implement a corrective action plan to bring variance within ±5% next period.`,
    ),
    '- Schedule a mid-period forecast refresh to update guidance based on actuals-to-date.',
    '- Share this report with cost-centre owners for accountability sign-off.',
    '',
    '---',
    '*Report generated by Morgan — Contoso Financial Digital Finance Analyst*',
  );

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// 2. createWeeklyBriefingContent
// ---------------------------------------------------------------------------

export function createWeeklyBriefingContent(params: {
  week_number: number;
  include_kpis: boolean;
}): string {
  const now    = new Date();
  const period = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const anomalyResult = detectAnomalies({ period, threshold_percent: 10 });

  const lines: string[] = [
    `# 📅 Weekly Finance Briefing — Week ${params.week_number}`,
    `**Period:** ${period}  |  **Prepared by:** Morgan, Digital Finance Analyst`,
    '',
    '---',
    '',
    '## Opening Summary',
    '',
    `This briefing covers financial performance for Week ${params.week_number} of ${now.getFullYear()}. ` +
      `${anomalyResult.totalAnomalies > 0
        ? `⚠️ ${anomalyResult.totalAnomalies} budget anomaly(ies) require attention.`
        : '✅ All categories are tracking within acceptable variance thresholds.'}`,
    '',
  ];

  if (params.include_kpis) {
    const kpis = getFinancialKPIs({ period });
    lines.push(
      '---',
      '',
      '## 📊 KPI Dashboard',
      '',
      '| KPI | Value |',
      '|-----|-------|',
      `| Net Revenue | ${usd(kpis.netRevenue)} |`,
      `| Gross Margin | ${kpis.grossMarginPct}% |`,
      `| EBITDA | ${usd(kpis.ebitda)} |`,
      `| Monthly Burn Rate | ${usd(kpis.burnRateMonthly)} |`,
      `| Cash Runway | ${kpis.cashRunwayMonths} months |`,
      `| Revenue Growth (MoM) | ${pctStr(kpis.revenueGrowthPct)} |`,
      '',
    );
  }

  lines.push(
    '---',
    '',
    '## 🔍 Notable Items',
    '',
  );

  if (anomalyResult.anomalies.length > 0) {
    anomalyResult.anomalies.forEach(a => {
      const sev = a.severity === 'critical' ? '🔴' : a.severity === 'warning' ? '🟡' : '🔵';
      lines.push(`- ${sev} **${a.category}**: ${pctStr(a.variancePct)} over budget — ${a.severity.toUpperCase()}`);
    });
  } else {
    lines.push('- No notable items this week. All categories within target.');
  }

  lines.push(
    '',
    '---',
    '',
    '## ✅ Actions Required',
    '',
    ...anomalyResult.anomalies.map(
      a => `- [ ] **${a.category} owner** to submit variance explanation by EOD Friday.`,
    ),
    '- [ ] Finance team to review actuals vs rolling forecast before week close.',
    '- [ ] CFO to approve any budget reallocations exceeding $25,000.',
    '',
    '---',
    '*Automated briefing by Morgan — Contoso Financial · Do not reply to this message*',
  );

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// 3. formatForTeams
// ---------------------------------------------------------------------------

/**
 * Convert markdown tables (which Teams bot messages do NOT render) into
 * readable bold-label lines.
 *
 * Input:
 *   | Category | Budget | Actual |
 *   |----------|--------|--------|
 *   | Revenue  | $4.94M | $4.88M |
 *
 * Output:
 *   **Revenue** · Budget: $4.94M · Actual: $4.88M
 */
function convertMarkdownTables(md: string): string {
  return md.replace(
    /^\|(.+)\|\r?\n\|[-|: ]+\|\r?\n((?:^\|.+\|\r?\n?)*)/gm,
    (fullMatch) => {
      const lines = fullMatch.trim().split(/\r?\n/).filter(Boolean);
      if (lines.length < 3) return fullMatch; // not a real table

      const headers = lines[0].split('|').filter(c => c.trim()).map(c => c.trim());
      const dataRows = lines.slice(2); // skip header + separator

      const converted = dataRows.map(line => {
        const cells = line.split('|').filter(c => c.trim()).map(c => c.trim());
        if (headers.length === 2) {
          // Simple key–value table → "**Key**: Value"
          return `**${cells[0] ?? ''}**: ${cells[1] ?? ''}`;
        }
        // Multi-column: first cell bold, rest as "Header: value" pairs
        return cells.map((cell, i) =>
          i === 0 ? `**${cell}**` : `${headers[i] ?? i}: ${cell}`
        ).join(' · ');
      });

      return converted.join('\n') + '\n';
    },
  );
}

export function formatForTeams(params: {
  content: string;
  message_type: 'alert' | 'report' | 'info';
}): string {
  const typeHeader: Record<string, string> = {
    alert:  '🚨 **FINANCE ALERT**',
    report: '📊 **FINANCE REPORT**',
    info:   'ℹ️ **FINANCE UPDATE**',
  };

  const header = typeHeader[params.message_type] ?? typeHeader.info;

  // Teams-compatible transformations:
  //   • Flatten headings (#, ##, ###) → bold text
  //   • Replace HR dashes with a unicode line
  //   • Convert markdown tables → readable label lines (Teams ignores table syntax)
  const trimmed = params.content
    .replace(/^#{1,6}\s+/gm, '**')
    .replace(/---+/g, '─────────────────────────')
    .slice(0, 20_000);

  const formatted = convertMarkdownTables(trimmed);

  return [
    header,
    '',
    formatted,
    '',
    `─────────────────────────`,
    `*Sent by Morgan · ${new Date().toUTCString()}*`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// OpenAI Tool Definitions
// ---------------------------------------------------------------------------

export const REPORT_TOOL_DEFINITIONS: ChatCompletionTool[] = [
  {
    type: 'function',
    function: {
      name: 'formatBudgetReport',
      description:
        'Generate a formatted Markdown budget vs actuals report for a given period, suitable for sending via Teams or email. Includes executive summary, detail table, anomaly highlights, and recommendations.',
      parameters: {
        type: 'object',
        properties: {
          period: {
            type: 'string',
            description: 'The financial period to report on, e.g. "2025-Q2" or "2025-06".',
          },
          include_charts: {
            type: 'boolean',
            description: 'Whether to include a chart placeholder / reference in the report.',
          },
        },
        required: ['period', 'include_charts'],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'createWeeklyBriefingContent',
      description:
        'Generate a complete weekly finance briefing in Markdown, including an opening summary, KPI dashboard (optional), notable items, and an action-required checklist.',
      parameters: {
        type: 'object',
        properties: {
          week_number: {
            type: 'number',
            description: 'The ISO week number of the year (1–53).',
          },
          include_kpis: {
            type: 'boolean',
            description: 'Whether to include the KPI dashboard section in the briefing.',
          },
        },
        required: ['week_number', 'include_kpis'],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'formatForTeams',
      description:
        'Convert a Markdown finance report or message into a Teams-friendly format with a type-specific header (alert / report / info).',
      parameters: {
        type: 'object',
        properties: {
          content: {
            type: 'string',
            description: 'The Markdown content to format for Teams.',
          },
          message_type: {
            type: 'string',
            enum: ['alert', 'report', 'info'],
            description: 'The type of message: "alert" for urgent issues, "report" for scheduled reports, "info" for general updates.',
          },
        },
        required: ['content', 'message_type'],
      },
    },
  },
];
